# Generated by Django 4.0.3 on 2022-03-26 10:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=250)),
                ('date', models.DateField(blank=True, default=datetime.datetime.now)),
                ('intro', models.TextField(blank=True)),
                ('text', models.TextField()),
                ('text_end', models.TextField(blank=True)),
                ('url', models.TextField(blank=True, max_length=250)),
                ('image1', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
    ]
