# Generated by Django 4.0.3 on 2022-03-07 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='technologies',
        ),
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.CharField(default='adjaythakoerdien', max_length=100),
        ),
    ]
