# Generated by Django 4.0.3 on 2022-03-21 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Intro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intro_text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SkillData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=100)),
                ('number', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='SkillOther',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=100)),
                ('number', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='SkillWeb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=100)),
                ('number', models.CharField(max_length=250)),
            ],
        ),
    ]
